# @package _global_

method:
  _target_: robobase.method.diffusion.Diffusion
  is_rl: false
  lr: 1e-4
  num_train_steps: ${num_pretrain_steps}
  num_diffusion_iters: 100
  adaptive_lr: true
  actor_grad_clip: null

  actor_model:
    _target_: robobase.models.diffusion_models.ConditionalUnet1D  # film_unet
    _partial_: true
    input_shapes: ???
    output_shape: ???
    sequence_length: ${action_sequence}
    diffusion_step_embed_dim: 256
    down_dims: [256, 512, 1024]
    kernel_size: 5
    n_groups: 8

  encoder_model:
    _target_: robobase.models.EncoderMultiViewVisionTransformer
    _partial_: true
    input_shape: ???

  view_fusion_model:
    _target_: robobase.models.FusionMultiCamFeature
    _partial_: true
    input_shape: ???
    mode: flatten
